# Build Package

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7  # must be 3.7 due to grpcio-tools==1.21.1

      - name: Install build requirements
        run: |
          pip install -r requirements.txt

      - name: Build package
        run: python -m ansys.tools.protos_generator ansys/api/mapdl/v0/

      - name: Upload package artifact to github actions
        uses: actions/upload-artifact@v2.2.1
        with:
          name: proto package
          path: dist/*.tar.gz
          retention-days: 7

      - name: Upload package to PyPi
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          pip install twine
          twine upload --skip-existing dist/*.tar.gz
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
          TWINE_REPOSITORY_URL: "https://upload.pypi.org/legacy/"

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
